spring:
  application:
    name: Gateway
  cloud:
    gateway:
      routes:
        - id: reclamation
          uri: lb://reclamation
          predicates:
            - Path=/reclamation/**
server:
  port: 8093

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
logging:
  level:
    org.springframework.cloud.gateway: DEBUG

